name: Enzo Landino
favicon: null
layout_spectrum: 0.75241
typography_spectrum: 0.9560815675649792
title: Enzo Landino - Speaker Podcaster Brand Correspondent
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e2925'
    - '#ffffff'
    - '#000022'
    - '#af8b69'
    - '#f8b03f'
  brandStrength: 1
  lightness: 0.6752724754624069
  saturation: 0.15423478255979717
  rhythmicContrast: 0.5
purpose: []
